
int = make_stack()

testBlock = {
    def 1
}

int.stack_push(block_ref(testBlock), [])
int.run

assert(int.error_message == "Expected identifier after def, found: 1")
