# break errors::InternalError::InternalError(std::string)
break circa::errors::CircaError::CircaError()
run
