
-- This once had a bug, the get_index was going out of range
for i in [0, 1, 2, 3]
    print('step: ' i)
    continue
