# break errors::InternalError::InternalError(std::string)
break errors::CircaError::CircaError()
run
